# Model arguments
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

dataset_name: open-r1/OpenR1-Math-220k ## this is just placeholder
dataset_prompt_column: problem ## this is just placeholder


# GDPO trainer config
bf16: true
use_vllm: true
do_eval: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-1.5B-Open-R1-GDPO
hub_strategy: every_save
learning_rate: 5.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_generations: 16
num_train_epochs: 1
output_dir: /lustre/fsw/portfolios/nvr/users/shihyangl/openr1_results/Qwen2.5-1.5B-gsm8k-GDPO-3-rewards-run3
overwrite_output_dir: true
per_device_eval_batch_size: 16
per_device_train_batch_size: 16
push_to_hub: false
apply_gdpo: True
report_to:
- wandb
wandb_project: "open-r1-gsm8k-3-rewards"
run_name: "Qwen2.5-1.5B-gsm8k-GDPO-run3"
save_strategy: "steps"
save_steps: 20
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
